### ISSUE TITLE
Random call stack size exceeded in binaries complied with node v12.2.0

### ISSUE THREAD

**Issue by peakji** [zeit/pkg#681]
Thanks for updating pkg to support node v12!

It seems that there is a weird bug causing random **Maximum call stack size exceeded** errors ONLY in binaries complied by pkg targeting node v12.2.0:

| | Binary compiled by `pkg` | Run directly through `node` |
| --- | --- | --- |
| node v10.15.3 | ✅ | ✅ |
| node v12.2.0 |`Maximum call stack size exceeded` | ✅ |

(Tested on Linux / CentOS 7)

Unfortunately, the original code is part of a proprietary software so I could not post it here. But since it does not deal with files, I'm pretty sure the issue is not related to the snapshot file system.

Here are some stack trace samples, seems fully random, the only thing in common is the `RangeError: Maximum call stack size exceeded`:

```
06:25:30 [22016]: events.js:196
06:25:30 [22016]: Reflect.apply(handler, this, args);
06:25:30 [22016]: ^
06:25:30 [22016]: RangeError: Maximum call stack size exceeded
06:25:30 [22016]: at Object.emit (events.js:196:13)
06:25:30 [22016]: at endReadableNT (_stream_readable.js:1130:12)
06:25:30 [22016]: at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

```
06:07:11 [11185]: _stream_transform.js:140
06:07:11 [11185]: this._flush((er, data) => {
06:07:11 [11185]: ^
06:07:11 [11185]: RangeError: Maximum call stack size exceeded
06:07:11 [11185]: at String.replace (<anonymous>)
06:07:11 [11185]: at Object.prefinish (_stream_transform.js:140:10)
06:07:11 [11185]: at Object.emit (events.js:196:13)
```

```
06:18:41 [18060]: internal/timers.js:531
06:18:41 [18060]: timer._onTimeout();
06:18:41 [18060]: ^
06:18:41 [18060]: RangeError: Maximum call stack size exceeded
06:18:41 [18060]: at listOnTimeout (internal/timers.js:531:17)
06:18:41 [18060]: at processTimers (internal/timers.js:475:7)
```

**Comment by OneBitAhead** [comment]
Same error occurs on  Linux / Ubuntu.

Indeed it seems to be VERY random. Here are some of my stack traces:

```
/snapshot/oba-core/node_modules/cron/lib/cron.js:562
			this._callbacks[i].call(this.context, this.onComplete);
			                   ^

RangeError: Maximum call stack size exceeded
    at CronJob.fireOnTick (/snapshot/oba-core/node_modules/cron/lib/cron.js:562:23)
    at Timeout.callbackWrapper [as _onTimeout] (/snapshot/oba-core/node_modules/cron/lib/cron.js:629:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
```
events.js:196
    Reflect.apply(handler, this, args);
            ^

RangeError: Maximum call stack size exceeded
    at process.emit (events.js:196:13)
    at processPromiseRejections (internal/process/promises.js:165:18)
    at processTicksAndRejections (internal/process/task_queues.js:90:32)
```

Besides: You do a great job with `pkg`!

**Comment by OneBitAhead** [comment]
Because "randomness" of bugs is a pain in the *** for a programmer (and nothing to work with easily) I compiled our product code together with a set of round about 300 unit tests. 
These tests use a lot of I/O fs commands, event emitters, http server things, etc.

I ran them multiple times hoping to provide a better error description: BUT every time the error occurs at different tests and code segments. So I cannot provide a better description.

**Comment by simlevesque** [comment]
Same here. Ubuntu. Not using the file system. It happens at random moments and I'm on 12.2. If I run the program with Node 12.2 without pkg, it works every time. It's only when the app is packaged with pkg using 12.2.

**Comment by cheukyin21hk** [comment]
Same problem here, Tested on Window(win10 and win server 2016).

**Comment by tarkh** [comment]
Same here, getting this error in heavy load loops ONLY when program packed with PKG:
`UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded`

**Comment by tarkh** [comment]
Well, tried to create custom build with latest master version of Node 12.x branch and got the same STACK SIZE error... So maybe its patch related. Waiting for fix or workaround, because on this moment it is almost impossible to work with Node 12 in PKG.
Btw thanx for great soft!

**Comment by tobiasmuecksch** [comment]
I can confirm this happens on Debian 9.8 too

**Comment by luxmeter** [comment]
Same here on Amazon Linux AMI.
I though it would be my fault and tried to improve my script in several ways but it didn't work.
I'm glad I found this thread. I can also confirm that the issue does not appear with an older version of NodeJs (v10).

**Comment by tumasst** [comment]
CentOS Linux release 7.6.1810, node v12, same problem.

node v10 - ok

**Comment by tobiasmuecksch** [comment]
@igorklopov Any thoughts on this issue?

**Comment by bergheim** [comment]
Can confirm the same issue on 5.1.11-arch1-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux. Works fine with node10.

**Comment by whisper-bye** [comment]
node v12.6.0 macOS 10.14

**Comment by itayayuichiro** [comment]
@peakji 
Which version of `pkg` did you use?

**Comment by peakji** [comment]
@itayayuichiro I'm using the latest pkg v4.4.0 which depends on pkg-fetch v2.6.2.

**Comment by itayayuichiro** [comment]
Many thanks.

**Comment by stripedpajamas** [comment]
Facing similar random crashes with this error:

```
internal/timers.js:531
  timer._onTimeout();
        ^
  RangeError: Maximum call stack size exceeded
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

OS: Ubuntu 19.04 x86_64
Kernel: 5.0.0-20-generic

pkg version: pkg@4.4.0

code that was running:

```
setInterval(asyncfunction, 1500)
```

binary created with: 

```
npx pkg -t latest-linux-x64 -o out index.js
```

**Comment by eg-be** [comment]
I'm running into a 

```
RangeError: Maximum call stack size exceeded
    at add_all_in (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1177:26)
    at Subscription._collectNotificationData (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1103:13)
    at Subscription._harvestMonitoredItems (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:1140:39)
    at Subscription.process_subscription (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:788:18)
    at Subscription._tick (E:\snapshot\SimulationServer\node_modules\node-opcua-server\dist\server_subscription.js:917:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
too, with packaged binaries.

On windows 7
node 12.6.0
pkg version: pkg@4.4.0

**Comment by odellcraig** [comment]
I can also confirm the 

```RangeError: Maximum call stack size exceeded```

Using node v12.7.0

Sorry, I don't have much other detail as it also seems random for me.

**Comment by MattSandy** [comment]
Having the same issue as well, with a very simple script. Works in command line, doesn't work compiled with pkg. 
```
const Crawler = require("js-crawler");
const cheerio = require('cheerio');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Enter Domain? ', (answer) => {
    get_phone(answer);
});
var $ = {};
function get_phone(domain) {
    new Crawler().configure({ depth: 2, maxRequestsPerSecond: 2 }).crawl("http://" + domain, function (page) {
        $ = cheerio.load(page.body);
    }, null, function onAllFinished(crawledUrls) {
        console.log('FINISHED');
        console.log(crawledUrls);
        process.exit();
    });
}
```

The output shows

```
Enter Domain? github.com
/snapshot/contact-info/node_modules/js-crawler/crawler.js:167
    this.onAllFinished && this.onAllFinished(this.crawledUrls);
                               ^

RangeError: Maximum call stack size exceeded
    at Crawler._finishedCrawling (/snapshot/contact-info/node_modules/js-crawler/crawler.js:167:32)
    at Request._callback (/snapshot/contact-info/node_modules/js-crawler/crawler.js:188:12)
    at Request.callback (/snapshot/contact-info/node_modules/request/request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (/snapshot/contact-info/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (/snapshot/contact-info/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by theebasso** [comment]
Same error for me.
Does someone have any lead ? Workaround ?

**Comment by tobiasmuecksch** [comment]
@theebasso The only currently known workaround is to downgrade to nodejs 10.

**Comment by RezaErfani67** [comment]
any support?

**Comment by gluwer** [comment]
We have encountered the same exception using 12.2 x86 build on Windows. It happens after some time (several hours later most of the time), but always in the same place in Cosmos DB library.

The stack trace is (for RangeError - Maximum call stack size exceeded):

| 0 | {"assembly":"at new ParallelQueryExecutionContextBase (node_modules\\@azure\\cosmos\\dist\\index.js:2866:24)","method":"new ParallelQueryExecutionContextBase (node_modules\\","level":0,"line":2866,"fileName":"azure\\cosmos\\dist\\index.js"}
  | 1 | {"assembly":"at new OrderByQueryExecutionContext (node_modules\\@azure\\cosmos\\dist\\index.js:3370:13)","method":"new OrderByQueryExecutionContext (node_modules\\","level":1,"line":3370,"fileName":"azure\\cosmos\\dist\\index.js"}
  | 2 | {"assembly":"at new PipelinedQueryExecutionContext (node_modules\\@azure\\cosmos\\dist\\index.js:3700:62)","method":"new PipelinedQueryExecutionContext (node_modules\\","level":2,"line":3700,"fileName":"azure\\cosmos\\dist\\index.js"}
  | 3 | {"assembly":"at QueryIterator.<anonymous> (node_modules\\@azure\\cosmos\\dist\\index.js:3966:46

What is interesting, when it happens once, the exception is now on always triggered in the same place in every case until the node process is restarted. We now also downgraded to node 10 to confirm it is node 12 related.

**Comment by jhonore** [comment]
The same error for me but with a little difference :
It's run on Macos (*compiled by PKG* and *Node*)
It's goes to "Maximum call stack size exceeded" on my Debian 8.11 (compiled version)

**Comment by armenr** [comment]
We're getting the same thing on our code compiled with pkg - and it isn't clear why or how.

**Comment by rweads0520** [comment]
Downgrade to node 10 is not such a magic key when dependent on features in node 11+.

**Comment by tobiasmuecksch** [comment]
Yup. But nobody in charge seems to care...

**Comment by armenr** [comment]
We've had terrible luck when it comes to getting answers out of pkg or ncc - and the spectrum communities for zeit's various projects (NextJS, pkg, ncc) are so noisy (and the interface so bad) that the people with knowledge who *could* be answering questions simply aren't. Opening issues on GitHub isn't going so well either.

**Comment by RezaErfani67** [comment]
i use worker-threads that compatible with v11 and 12.... i cant install node 10...
really not exist any solution?

**Comment by tonywoode** [comment]
The above is with windows btw (note extra unrelated issue with 4.4.0 confounding a downgrade). Not a good day for my otherwise fantastic experience with pkg

**Comment by EscolanoGarnica** [comment]
Same problem for me, node 12.2.0 running in raspbian,  pkg -> 4.4.0

**Comment by armenr** [comment]
We've abandoned pkg altogether, as much as it pains us. The lack of support/response is more than a little concerning, and we can't ship without some assurances.

The really terrible alternative to get NEARLY the same *practical effect* is going to have to be bloody Docker, which we've avoided like the plague to this point.

**Comment by poseidonCore** [comment]
I have just now abandoned pkg too and moved over to nexe/nexe.

**Comment by OneBitAhead** [comment]
We did the same with our product (since no official statement or any reaction has been given here): moving on to [nexe](https://github.com/nexe/nexe).
Yesterday I did some tests with node.js 12.12.0 and nexe and it works like **charm** ;)

**Comment by odellcraig** [comment]
Does anyone know if nexe supports all three platforms (linux, maxos,
windows)? I know I'm being a bit lazy here, but it's not obvious from a
first glance at nexe docs.

**Comment by poseidonCore** [comment]
@odellcraig, yes: [targets](https://github.com/nexe/nexe#target-string--object)

The major problem that I had with nexe was that [edge-js](https://github.com/agracio/edge-js) did not integrate as well, but I decided to split this into a separate .NET Core service and things are more stable and easier to build now anyway ... and I can now keep up with Node 12.

Be aware that nexe uses a different virtual file system concept. Instead of creating a separate virtual location for the compiled program to run in, it seems to just overlay a virtual file system rooted in the directory of the executable, and then do some internal redirection.

I'm new to nexe, but it literally took me just a few minutes to resolve most of the problems in my code.

**Comment by btsimonh** [comment]
I've been using a modified nexe in production for 2 years, and yes, I've built for windows, linux and OSX.
OSX signing is a challenge - see some of the nexe issues, one has a comment on how I overcame this.  (basically you can't really append to the end of the exe in OSX and sign, so I put all the filesystem access stuff in node internals, and have a side file containing the FS image(s).)
I've build using nexe & node 6.9.1-6.9.11, and latterly 12.10.0.
But my Nexe uses a different filesystem again, with native module support.

**Comment by odellcraig** [comment]
@poseidonCore @btsimonh Thanks for your responses (ironic that they're on this thread :))! I'm going to switch to nexe.

**Comment by wenbob** [comment]
I am trying to bypass this bug by changing stack-size, but I am not sure if this is the correct operation:

```
pkg app.js --options stack-size=20480
```

**Comment by armenr** [comment]
For anyone still thinking about what to do --> we moved over to `ncc`

Packaging NextJS (serverless targetted builds EVEN though it's running on an EC2) + custom server w/ ncc was a bit of a challenge, but we've got everything deploying and working without any dependencies.

**Comment by eddiewang** [comment]
@armenr I'd love to see an example of how you packaged up a nextjs app using `ncc`. looking to do the same myself.

**Comment by julianpoemp** [comment]
I'm currently developing a backup script, that downloads a FTP directory. It took me almost 5 days to find the solution: I thought it's an error in my code, but It's because of pkg. If I use my script directly via node, it works like a charm. I was almost giving up before I found this issue. I will look for an alternative, thanks!

**Comment by RezaErfani67** [comment]
i go to build with webpack and minify and obfuscate it

**Comment by karanssj4** [comment]
any update on this?

**Comment by armenr** [comment]
> @armenr I'd love to see an example of how you packaged up a nextjs app using `ncc`. looking to do the same myself.

What's your preferred method of communication? Let's square up and I can walk you through it. If it seems to be something stable and repeatable, we can throw a gist together to share with others :)

**Comment by MichaelGatesDev** [comment]
Considering that everyone else here is migrating due to this issue being ignored, I will also be jumping ship. A shame, really, considering how great of a resource pkg has been to my project. But it's just not acceptable to have to downgrade to v10 of Node when my project relies on v12 features of the file system. 

Issue occurs on Windows and Ubuntu both, and only in the packaged binaries. It also can be somewhat random. I tried profiling and came out empty handed.

**Comment by fsoft72** [comment]
I have the same issue with pkg.
Luckily enough I decided to google for the stack size exception problem and found this thread ;-)
I've just switched to nexe and I'll never look back again.

**Comment by igorklopov** [comment]
Please try using `--public` cli option in this case

**Comment by MichaelGatesDev** [comment]
> Please try using `--public` cli option in this case

Could you expand on your comment? What will `--public` do?

**Comment by igorklopov** [comment]
`--public` doesn't strip sources and leaves them inside the compiled binary, if it is acceptable

**Comment by armenr** [comment]
Leaving the source inside the binary will solve for the call stack blowing its lid randomly? @igorklopov

**Comment by mojzu** [comment]
I added the --public flag the pkg options, it seems to make the "RangeError: Maximum call stack size exceeded" error less frequent, but it does still happen.

**Comment by karanssj4** [comment]
@igorklopov are there any plans to address this?

**Comment by igorklopov** [comment]
The root cause is found. Shipping soon

**Comment by MichaelGatesDev** [comment]
Great. Nexe is a cool alternative but there's a fatal bug right now on Windows machines :skull: 

Can't wait for the update to switch back to pkg

**Comment by sgoll** [comment]
> Great. Nexe is a cool alternative but there's a fatal bug right now on Windows machines 💀

Since a lot of people have moved to `nexe` due to this issue, can you tell us more about that fatal bug? Is it worth switching back to `pkg`?

**Comment by MichaelGatesDev** [comment]
> > Great. Nexe is a cool alternative but there's a fatal bug right now on Windows machines 💀
> 
> Since a lot of people have moved to `nexe` due to this issue, can you tell us more about that fatal bug? Is it worth switching back to `pkg`?

https://github.com/nexe/nexe/pull/692
https://github.com/nexe/nexe/pull/701

Causes the application to only be runnable in specific instances. I should say 'not usable for production' rather than 'fatal' because it does not cause the application to crash, but rather not to start at all.

**Comment by tarkh** [comment]
@igorklopov Thanx, compiled and tested on MacOS Catalina, so far so good without random call stack exceeded! Finally we can move on)

**Comment by RezaErfani67** [comment]
please update npm package.
@igorklopov

**Comment by igorklopov** [comment]
Fixed in 4.4.1. Please try

**Comment by RezaErfani67** [comment]
@igorklopov 
is it OK  with version 13.xx of nodejs?
did you test it?

**Comment by bergheim** [comment]
I have tested this for a bit now, and so far it works like a charm. Will update if it ever comes up again.

Hoorayy @igorklopov !

**Comment by OneBitAhead** [comment]
Running all our product test cases again: works like charm (node version 12.13)

Thanks @igorklopov  !!

**Comment by mojzu** [comment]
Updated to 4.4.1, haven't seen this error again after testing. Thank you for resolving this, and for the rest of pkg!

**Comment by geomad** [comment]
I can confirm the error persists on pkg 4.4.1 with node12.2.0-linux-armv7

**Comment by ataft** [comment]
@geomad As per https://github.com/zeit/pkg-fetch/pull/76/files?file-filters%5B%5D=.json, it looks like the fix was applied to the following:
- v12.13.1
- v10.17.0
- v8.16.2

**Comment by arkasaha2** [comment]
pkg v4.4.1 with node v12.3.1 has been working fine for me..

Thanks @igorklopov !!

**Comment by shusson** [comment]
also confirmed fixed in pkg 4.4.2 with node 12.4.0

**Comment by peakji** [comment]
I guess it is safe to close the issue now 🚀

**Comment by denoww** [comment]
I can confirm the error persists on pkg 4.4.1 with node12.2.0-linux-armv7

**Comment by ataft** [comment]
@denoww you can see from these comments that the fix was not applied to 12.2.0. It's on 12.13.1 and above.

**Comment by sgoll** [comment]
> @denoww you can see from these comments that the fix was not applied to 12.2.0. It's on 12.13.1 and above.

@ataft Unfortunately, `12.2.0` is still the latest prebuilt release for the `armv7` platform: https://github.com/vercel/pkg-fetch/releases

I myself was bitten by this issue just now.

**Comment by Ks89** [comment]
I'm having the same issue. The latest release available for ARMv7 is 12.2.0 and it's very old and affected by this issue.
Is it possible to update prebuilt releases for ARMV7 adding both 12 and 14 latest stable releases (they are both LTS).

thank u.
